development:
  sessions:
    default:
      database: foundation_development
      hosts: 
        - localhost:27017

test:
  sessions:
    default:
      database: foundation_test
      hosts: 
        - localhost:27017

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
